image:
  file: Dockerfile
  
  
tasks:
  -  command: mkdir /workspace/gitpod-po-util/logs                                                                    &&
              touch /workspace/gitpod-po-util/logs/gitpod-install-log.txt                                             &&

       

              echo "Starting .gitpod.yml installation" &>>  /workspace/gitpod-po-util/logs/gitpod-install-log.txt     &&
              
              sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"             &&
              export PATH=${PATH}:/home/gitpod/.linuxbrew/bin                                                         &&
              
              
              echo "Starting Po"                   &>>  /workspace/gitpod-po-util/logs/gitpod-install-log.txt         &&   
              
              
              
              
              echo "Ending .gitpod.yml installation"  &>>   /workspace/po/logs/gitpod-install-log.txt    
              
              
     
